services:
  backend:
    build: ./backend
    container_name: eli5-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: eli5-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped